# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  configuration: 'Release'
  projectPath::  '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- task: UseDotNet@2
  displayName: 'Install .Net Core SKD'
  inputs:
   packageType: sdk
   version: '2.x'

- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: build
    configuration: $(configuration)
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Pack the package'
  inputs:
   command: 'pack'
   configuration: $(configuration)
   packagesToPack: '**/*.csproj'
   nobuild: true
   versioningScheme: 'byPrereleaseNumber'
   majorVersion: '1'
   minorVersion: '0'
   patchVersion: '0'


